# Site settings
title: Andrew Mao @ 863.14
email: "mizzao _AT_ gmail.com"

description: > # this means to ignore newlines until "baseurl:"
  Blog for MAS 863 made in Jekyll.
  See the About page for more details.

# the subpath of your site, e.g. /blog/
baseurl: "/classes/863.14/people/andrew_mao" 

# the base hostname & protocol for your site
url: "http://fab.cba.mit.edu" 
twitter_username: mizzao
github_username:  mizzao

# Build settings
markdown: kramdown
